[package]
name = "RustRPG"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
indexmap = "2.7.1"
once_cell = "1.20.3"
chrono = { version = "0.4.40", features = ["serde"] }
fs = "0.0.5"

